---
title: "台股動能策略實證 — 價格動能"
description: "價格動能策略在台股"
date: "2026-03-10"
categories: [系列文章]
#image: ""
---

## 何謂價格動能
價格動能策略源自於 Jegadeesh 與 Titman (1993) 的研究[^1]，他們針對 1965 至 1989 年的**美股市場**進行動能策略的實證研究。

作者利用過去 $J$ 個月的歷史資料計算每隻股票的報酬率作為價格動能訊號，據此買進過去贏家 (動能最強的 10%) 賣出過去輸家 (動能最弱的 10%) 建構多空投資組合，持有 $K$ 個月。

**論文的主要論點在於：短期反轉、中期動能、長期反轉**

### 短期反轉
當包含最近的股價資料時，會有短期反轉的現象。也就是近期的強勢股反而接下來短期走弱。因此作者在計算動能訊號時分為兩種版本，分別是跳過最近一周的股價資料與包含最新的股價資料，結果顯示跳過版本的表現較佳。

::: {.callout-note}
## 補充說明
儘管 Jegadeesh 與 Titman (1993) 是跳過最近一周來排除短期反轉，後續的文獻為了避免短期反轉則都是以跳過最近一個月的資料為主，如 Gong et al. (2015)[^2] 。
:::

### 中期動能
作者發現多空投資組合持有期介於 3 到 12 個月時，具有正的超額報酬。也就是說持有期為一年內時，過去的贏家也會是接下來的贏家、過去的輸家則會繼續是輸家。

作者認為這樣的報酬差異可以用反應不足來解釋，也就是說投資人對於股票基本面變化的反應不足，當前價格並未完全反映價值。

同時文章也提到動能策略最佳的參數組合為：$J=12, K=3$ 並且跳過最近一周；而最差的參數組合為：$J=3, K=3$ 並且不跳過最近一周。

也就是說價格動能策略在**較長的形成期 + 較短的持有期 + 避免短期反轉**的狀況下表現最好。

::: {.callout-note}
## 補充說明
由於論文的參數選擇僅包含 $\{3,6,9,12\}$，因此後續台股實證分析時，我會將參數選擇擴大為 $\{1, 3,6,9,12, 18, 24\}$。

目的是為了確認在其他條件不變下，超過一年的形成期對於報酬率有何影響，以及更短的持有期是否能進一步提高報酬率。
:::

### 長期反轉
與中期動能不同，作者觀察到當多空投資組合的持有期超過 12 個月時，報酬率反而由正轉負，過去的贏家反而是接下來的輸家、過去的輸家則變成贏家。

## 價格動能的計算方式
價格動能本質上就是去計算每隻股票過去 $J$ 個月的總報酬，報酬率越高表示訊號越強。由於有配股配息的問題，因此不能使用一般的收盤價計算價格動能，而是要使用**調整後收盤價**計算，計算方式也非常簡單：

$$
MOM_{t,J} = \dfrac{P_t}{P_{t-J}} - 1
$$

這裡的 $P_t$ 表示的是第 $t$ 月底的調整後收盤價，同理 $P_{t-J}$ 是 $J$ 個月前的月底調整後收盤價。若在計算上要忽略最近一個月的資料也非常容易，只要取上個月的動能訊號 $MOM_{t-1,J}$ 即可。

實際回測時的價格動能函數如下：

```python
def compute_factor(j: int, 
                   skip_current_month: bool) -> pd.DataFrame:
    """
    價格動能因子：過去 j 個月的總報酬率
    skip_current_month=True 時跳過最近一個月
    """
    if skip_current_month:
        return 調整後收盤價.pct_change(j).shift(1).where(股票池濾網)
    else:
        return 調整後收盤價.pct_change(j).where(股票池濾網)
```

## 台股實證結果
由於考量放空在實務中的難度與成本，因此以投資來說我們更加在意的是做多動能投資組合能否擊敗大盤，而非論文中的多空投資組合是否可以帶來超額報酬。

在我們設定的回測樣本期間內 (2011-2025)，大盤 (含息) 的年化月均報酬率為 **0.1257**，也就是說動能策略的年化月均報酬率至少要大於 0.1257 ，才能在後續考慮手續費與報酬波動度下，和大盤有一拚的機會，否則長期買進並持有大盤會是更好的選擇。

因此在接下來的分析中，我主要會以價格動能策略中的多頭部位為主，也就是做多動能最強的 10% 贏家股票，並且進行以下分析：

- JK 參數分析
- 報酬單調性分析
- 條件排序分析
- 策略績效分析

::: {.callout-tip}
## 分析框架
所有的分析框架都與 [框架設定](../台股動能策略實證 — 框架設定/index.qmd) 這篇文章相同，故這裡不再複述。
:::


### JK 參數分析

參數分析的目的在於探討在不同參數之下，策略的表現是否存在差異，且我們預期這個差異是有規則可循。以動能策略來說，隨持有期越長，因投資人反應不足造成的潛在獲利逐漸消失，因此預期報酬率也會逐漸降低。

此外，一個穩定的策略不應該出現孤立的報酬率峰值，也就是說最佳參數附近的表現也應該都還不錯，而不是只有單一組合特別好、其他都很差，避免過度擬合的疑慮。

本章節會分成三個部分：

**第一部分：全樣本分析**\
在全樣本下，檢視三種投資組合在不同參數的報酬表現，分別是贏家組合、輸家組合、以及多空組合，同時也會比較是否忽略最近一個月資料的差異，因此總共會有 6 張表。

**第二部分：滾動性參數分析**\
將樣本期間 2011-2025 以 5 年為一個單位建構滾動樣本區間，查看每個區間的最佳參數為何，因此一共有 11 個滾動樣本區間 (2011-2015, 2012-2016, ..., 2021-2025)。

**第三部分：考慮交易成本後的贏家組合**\
在全樣本下，檢視兩種贏家組合在考慮交易成本後的實際月均報酬為何以及是否贏過大盤。

#### 全樣本分析
::: {.panel-tabset}
## 贏家組合 (no-skip) 
| J / K | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **1** | 0.1285 | 0.1336 | 0.1272 | 0.1206 | 0.1143 | 0.1026 | 0.1026 |
| **3** | 0.1740 | 0.1583 | 0.1519 | 0.1397 | 0.1236 | 0.1052 | 0.1048 |
| **6** | 0.1901 | 0.1736 | 0.1600 | 0.1345 | 0.1167 | 0.0980 | 0.1005 |
| **9** | 0.1850 | 0.1652 | 0.1364 | 0.1137 | 0.0980 | 0.0864 | 0.0887 |
| **12**| 0.1347 | 0.1136 | 0.0992 | 0.0846 | 0.0773 | 0.0755 | 0.0800 |
| **18**| 0.1038 | 0.0916 | 0.0790 | 0.0729 | 0.0682 | 0.0683 | 0.0773 |
| **24**| 0.0866 | 0.0801 | 0.0731 | 0.0663 | 0.0653 | 0.0678 | 0.0772 |


## 贏家組合 (skip)
| J / K | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **1** | 0.1477 | 0.1336 | 0.1248 | 0.1189 | 0.1099 | 0.1001 | 0.1013 |
| **3** | 0.1616 | 0.1497 | 0.1434 | 0.1279 | 0.1146 | 0.0990 | 0.1014 |
| **6** | 0.1649 | 0.1596 | 0.1416 | 0.1161 | 0.1023 | 0.0898 | 0.0943 |
| **9** | 0.1633 | 0.1416 | 0.1122 | 0.0936 | 0.0817 | 0.0771 | 0.0815 |
| **12**| 0.1094 | 0.0975 | 0.0825 | 0.0706 | 0.0677 | 0.0696 | 0.0768 |
| **18**| 0.0861 | 0.0739 | 0.0677 | 0.0631 | 0.0613 | 0.0641 | 0.0751 |
| **24**| 0.0781 | 0.0724 | 0.0657 | 0.0611 | 0.0621 | 0.0669 | 0.0766 |
:::
<br>
從贏家組合的兩張參數表可以獲得以下發現：

- **持有期越長，報酬率越低**\
除了 $J,K = 1,1$ 外，觀察每個 row 可以發現，隨著持有期的增加，報酬率大致上逐漸降低，符合動能策略的假設。
- **形成期並非越長越好**\
隨者形成期逐漸增加，報酬率也逐漸提高，在 6 個月、9 個月時達到相對高峰，隨後下降。Jegadeesh 與 Titman (1993) 針對美股的研究發現最佳的形成期為 12 個月，而在台股反而是更短的形成期 (6 或 9 個月) 策略表現更佳。
- **排除最近一個月有好有壞**\
若排除最近一個月的資料，可以觀察到 $J,K = 1,1$ 的投資組合報酬率明顯提升 (0.1285 vs 0.1477)，但其他投資組合的報酬率卻都一致性的下降，顯示排除最近一個月的資料確實可以避免短期反轉效應，但也使動能訊號的時效性減少，降低整體報酬。

::: {.callout-note}
## 以濾網取代排除近期資料
Jegadeesh 與 Titman (2001) [^3] 針對價格動能策略的樣本外研究時，放棄使用跳過最近資料的方式，改採選股池濾網來處理短期反轉效應。他們發現實際上造成反轉效應的原因絕大部分是因為**低價股**造成的，因此建構投資組合時剔除 5 美元以下低價股。
:::

::: {.panel-tabset}
## 輸家組合 (no-skip) 

| J / K | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **1** | 0.0743 | 0.0661 | 0.0639 | 0.0613 | 0.0665 | 0.0788 | 0.0837 |
| **3** | 0.0708 | 0.0467 | 0.0496 | 0.0491 | 0.0596 | 0.0746 | 0.0799 |
| **6** | 0.0560 | 0.0342 | 0.0366 | 0.0497 | 0.0634 | 0.0826 | 0.0842 |
| **9** | 0.0464 | 0.0269 | 0.0470 | 0.0621 | 0.0759 | 0.0888 | 0.0907 |
| **12**| 0.0409 | 0.0466 | 0.0669 | 0.0821 | 0.0925 | 0.0962 | 0.0968 |
| **18**| 0.0851 | 0.0850 | 0.0988 | 0.0999 | 0.1030 | 0.1067 | 0.1030 |
| **24**| 0.0912 | 0.0898 | 0.1006 | 0.1038 | 0.1070 | 0.1064 | 0.1030 |


## 輸家組合 (skip)
| J / K | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **1** | 0.0592 | 0.0562 | 0.0621 | 0.0609 | 0.0658 | 0.0768 | 0.0814 |
| **3** | 0.0281 | 0.0384 | 0.0455 | 0.0491 | 0.0616 | 0.0773 | 0.0810 |
| **6** | 0.0318 | 0.0272 | 0.0388 | 0.0559 | 0.0709 | 0.0851 | 0.0870 |
| **9** | 0.0250 | 0.0260 | 0.0538 | 0.0697 | 0.0830 | 0.0910 | 0.0922 |
| **12**| 0.0443 | 0.0579 | 0.0793 | 0.0932 | 0.0997 | 0.1013 | 0.0997 |
| **18**| 0.0795 | 0.0890 | 0.1008 | 0.1041 | 0.1063 | 0.1085 | 0.1043 |
| **24**| 0.0887 | 0.0941 | 0.1024 | 0.1081 | 0.1091 | 0.1074 | 0.1030 |
:::
<br>
輸家組合的報酬呈現的是動能策略的另一個視角，它的整體報酬分布呈現了一個驚人事實：

- **不論任何 J、K 組合，有無排除最近資料，做多輸家組合的報酬率均無法超越大盤**\
以形成期而言，即使短期 (1-3 個月)、長期輸家 (18-24 個月) 看起來較中期輸家 (6-12 個月) 更有反轉的現象，報酬率較高，但整體而言仍低於大盤。以持有期而言，即使較長的持有期也會有反轉的現象使輸家組合報酬提高，但仍低於大盤。

::: {.callout-tip}
## 順勢而為、不逆市操作
散戶往往有較強的處置效應，也就是股票漲了就趕快賣出實現獲利，跌了卻不願賣出實現損失。而不願賣出手上的輸家股票，本質上就是**做多輸家組合**。從實證結果來看，這樣的策略報酬是低於大盤的。
:::

::: {.panel-tabset}
## 多空組合 (no-skip) 

| J / K | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **1** | 0.0542 | 0.0674 | 0.0633 | 0.0593 | 0.0478 | 0.0239 | 0.0189 |
| **3** | 0.1032 | 0.1116 | 0.1023 | 0.0907 | 0.0640 | 0.0306 | 0.0249 |
| **6** | 0.1341 | 0.1394 | 0.1234 | 0.0848 | 0.0533 | 0.0153 | 0.0163 |
| **9** | 0.1386 | 0.1383 | 0.0894 | 0.0516 | 0.0221 | -0.0024 | -0.0020 |
| **12**| 0.0938 | 0.0669 | 0.0323 | 0.0025 | -0.0153 | -0.0207 | -0.0169 |
| **18**| 0.0187 | 0.0066 | -0.0198 | -0.0270 | -0.0347 | -0.0383 | -0.0257 |
| **24**| -0.0045 | -0.0096 | -0.0275 | -0.0376 | -0.0417 | -0.0387 | -0.0259 |

## 多空組合 (skip)

| J / K | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **1** | 0.0885 | 0.0775 | 0.0627 | 0.0580 | 0.0441 | 0.0233 | 0.0199 |
| **3** | 0.1335 | 0.1113 | 0.0980 | 0.0788 | 0.0530 | 0.0217 | 0.0203 |
| **6** | 0.1331 | 0.1323 | 0.1028 | 0.0602 | 0.0315 | 0.0047 | 0.0072 |
| **9** | 0.1383 | 0.1156 | 0.0584 | 0.0239 | -0.0013 | -0.0138 | -0.0107 |
| **12**| 0.0651 | 0.0396 | 0.0031 | -0.0226 | -0.0320 | -0.0317 | -0.0229 |
| **18**| 0.0066 | -0.0150 | -0.0331 | -0.0410 | -0.0450 | -0.0443 | -0.0293 |
| **24**| -0.0106 | -0.0217 | -0.0367 | -0.0470 | -0.0470 | -0.0405 | -0.0264 |
:::
<br>
多空投資組合的報酬為**贏家組合 - 輸家組合**而得，符合文獻提到：**短期反轉、中期動能、長期反轉**的結論，但就像在贏家組合所討論的，跳過最近資料有好有壞。

值得注意的是考慮最近資料的多空組合報酬僅在 $J=6, 9$ 且 $K=1, 3$ 時可以擊敗大盤，但差異也不明顯，這也是為何在學術文獻研究台股動能溢酬時，得出動能溢酬在台股較弱的原因。但就投資人來說，我們更加關心做多動能贏家股票能否帶來超越大盤的報酬。

::: {.callout-note}
## 更短的持有期間
由於實證結果贏家股票的持有期間越短，年化月均報酬率越高。或許大家會好奇持有期如果更短，如：1 周、2 周則報酬率是否更高？

從周頻率資料的實證結果而言[^4]，在不考慮交易費用的狀況下，持有期 2-3 周的報酬率最高，但與持有期 1 個月的報酬率差異不大 (年化不到 1%)，且在考慮交易費用後，反而不如持有期 1 個月。
:::

::: {.callout-tip}
## 包含最新資料的 no-skip 版本
從全樣本的實證結果中，我們發現在形成期超過 1 個月後，跳過最新資料反而對整體報酬率有負向影響，因此接下來的分析都是**包含最新資料的 no-skip 版本**。
:::


#### 滾動性參數分析

滾動參數分析的目的在於分析不同時間窗口下的最佳參數 $J, K$ 是否存在不穩定的狀況，同時也比較不同時段的動能策略與大盤表現差異。

滾動性參數分析 1 是比較所有的 $J, K$ 組合，一共有 49 種，並找出在每個區間的最佳 $J, K$ 組合，以及組合最佳報酬率與同期大盤報酬率。而滾動性參數分析 2 則是近一步比較 $K = 1$ 的狀況下，$J=6, 9$ 時的報酬率差異。

::: {.panel-tabset}
## 滾動性參數分析 1

| 區間 | 最佳 $J$ | 最佳 $K$ | 最佳報酬 | 同期大盤 |
|:---:|:---:|:---:|:---:|:---:|
| 2011-2015 | 6 | 1 | 0.1173 | 0.0284 |
| 2012-2016 | 6 | 1 | 0.1945 | 0.0947 |
| 2013-2017 | 6 | 1 | 0.2335 | 0.1041 |
| 2014-2018 | 6 | 1 | 0.1247 | 0.0675 |
| 2015-2019 | 9 | 1 | 0.1665 | 0.0972 |
| 2016-2020 | 9 | 1 | 0.2259 | 0.1652 |
| 2017-2021 | 6 | 1 | 0.2793 | 0.1848 |
| 2018-2022 | 6 | 1 | 0.1976 | 0.1125 |
| 2019-2023 | 9 | 1 | 0.2916 | 0.1776 |
| 2020-2024 | 6 | 1 | 0.2836 | 0.1827 |
| 2021-2025 | 6 | 1 | 0.2388 | 0.1834 |

## 滾動性參數分析 2

| 區間 | $J=6$ | $J=9$ | 同期大盤 |
|:---:|:---:|:---:|:---:|
| 2011-2015 | 0.1173 | 0.1029 | 0.0284 |
| 2012-2016 | 0.1945 | 0.1860 | 0.0947 |
| 2013-2017 | 0.2335 | 0.2207 | 0.1041 |
| 2014-2018 | 0.1247 | 0.1090 | 0.0675 |
| 2015-2019 | 0.1596 | 0.1665 | 0.0972 |
| 2016-2020 | 0.2141 | 0.2259 | 0.1652 |
| 2017-2021 | 0.2793 | 0.2740 | 0.1848 |
| 2018-2022 | 0.1976 | 0.1862 | 0.1125 |
| 2019-2023 | 0.2913 | 0.2916 | 0.1776 |
| 2020-2024 | 0.2836 | 0.2714 | 0.1827 |
| 2021-2025 | 0.2388 | 0.2262 | 0.1834 |
| 平均 | 0.2122 | 0.2055 | 0.1271 |
:::
<br>
從上述兩張分析表我們可以獲得以下觀察：

- **最佳形成期參數略有差異**\
從分析 1 可以發現，不同區間下的最佳形成期不同，但不是 6 個月 (獲勝 8 次) 就是 9 個月 (獲勝 3 次)，因此整體來說仍比文獻上提到的美股最佳形成期 (12 個月) 還要短。
- **持有期最佳為 1 個月**\
從分析 1 可以發現，不論在任何區間下最佳持有期為 1 個月，這與文獻當中提到的短持有期報酬較高相符。
- **形成期 6 或 9 個月，報酬率接近**\
從分析 2 可以發現，兩者的報酬率在不同區間下儘管互有領先，但整體接近，且以平均而言年化差異不到 1%。這也表示價格動能策略在台股是較具穩定性的策略，因為不存在報酬率峰值，最佳參數附近的其他參數表現也都不錯。

::: {.callout-tip}
## 後續分析的參數選擇
$K=1$ 的設定較無異議，而 $J$ 的選擇由於平均來說 6 個月的報酬率較高，且在不同區間的獲勝次數較多。後續分析，除非另有說明，否則會以 $J=6$、$K=1$ 進行探討。
:::

#### 考慮交易成本後的贏家組合
下表是考慮交易成本後的贏家組合報酬率以及對應的年化交易成本，其中年化交易成本就是考慮交易成本前後報酬率的差值。為了方便觀察，我將超過大盤報酬率 (0.1257) 的投資組合加粗。

::: {.panel-tabset}
## 考慮交易成本的贏家組合

| | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** | 0.0665 | 0.1119 | 0.1156 | 0.1124 | 0.1078 | 0.0978 | 0.0986 |
| **3** | **0.1325** | **0.1371** | **0.1402** | **0.1313** | 0.1168 | 0.1001 | 0.1005 |
| **6** | **0.1579** | **0.1563** | **0.1487** | **0.1262** | 0.1099 | 0.0928 | 0.0961 |
| **9** | **0.1580** | **0.1501** | **0.1261** | 0.1056 | 0.0914 | 0.0813 | 0.0843 |
| **12** | 0.1101 | 0.0998 | 0.0897 | 0.0770 | 0.0707 | 0.0704 | 0.0756 |
| **18** | 0.0826 | 0.0796 | 0.0706 | 0.0661 | 0.0622 | 0.0634 | 0.0731 |
| **24** | 0.0673 | 0.0693 | 0.0654 | 0.0599 | 0.0597 | 0.0631 | 0.0730 |

## 年化交易成本

| | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** | 0.0620 | 0.0217 | 0.0116 | 0.0082 | 0.0065 | 0.0048 | 0.0040 |
| **3** | **0.0415** | **0.0213** | **0.0117** | **0.0084** | 0.0068 | 0.0051 | 0.0043 |
| **6** | **0.0322** | **0.0173** | **0.0113** | **0.0083** | 0.0068 | 0.0052 | 0.0044 |
| **9** | **0.0271** | **0.0151** | **0.0103** | 0.0081 | 0.0066 | 0.0051 | 0.0044 |
| **12** | 0.0246 | 0.0138 | 0.0095 | 0.0076 | 0.0065 | 0.0051 | 0.0044 |
| **18** | 0.0212 | 0.0119 | 0.0084 | 0.0069 | 0.0060 | 0.0049 | 0.0043 |
| **24** | 0.0193 | 0.0109 | 0.0077 | 0.0063 | 0.0056 | 0.0047 | 0.0041 |

:::
<br>
比較有趣的結果是在持有期 1 個月的狀況下，形成期 9 個月的動能策略在考慮交易費用後和形成期 6 個月的策略報酬率相當，而原本不考慮交易費用時是 6 個月的策略領先 0.5%，而造成差異的原因就是交易成本。

若觀察年化交易成本，可以發現價格動能策略的形成期越長，通常訊號越穩定，因此投資組合每次需要換倉的比例越低，使交易成本下降；而持有期越長也因為換倉的頻率降低使交易成本下降。

::: {.callout-warning}
## 訊號穩定 ≠ 訊號有效
即使形成期越長訊號越穩定，但我們也發現一年以上的形成期，動能策略並無法帶來勝過大盤的報酬。
:::

### 報酬單調性分析
上一節主要是分析策略在不同參數下的報酬表現，並分析參數穩定性。而在這節主要是檢查策略訊號是否在整個分布上都有預測力，而不只在極端值有效 (動能最強的 10% 與最弱的 10%)。

具體來說，就是把股票依據訊號強弱分成 10 組 (第 1 組最弱稱為 M1，第 10 組最強稱為 M10)，並檢視從最弱組到最強組，平均報酬率是否呈現單調遞增的關係，這回答了幾個問題：

- **訊號是否整體有效**\
若只有最強組表現好、其他組差不多，說明策略很可能只是在挑異常個股，而非系統性有效。
- **排除過擬合疑慮**\
孤立的報酬峰值（如只有第 10 組特別好、第 9 組跟第 5 組差不多）是過擬合的警訊。
- **量化多空擴散程度**\
從最弱組到最強組的報酬差距，反映策略訊號的鑑別能力有多強。

: $K=1$ 時，各持有期 ($J$) 的報酬單調性分析

| M / J | 1 | 3 | 6 | 9 | 12 | 18 | 24 |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** | 0.0743 | 0.0708 | 0.0560 | 0.0464 | 0.0409 | 0.0851 | 0.0912 |
| **2** | 0.0817 | **0.0415** | **0.0330** | **0.0416** | **0.0536** | **0.0835** | **0.0871** |
| **3** | 0.0972 | 0.0718 | 0.0756 | 0.0593 | 0.0656 | 0.0973 | 0.1004 |
| **4** | 0.0988 | 0.0728 | **0.0755** | 0.0739 | 0.0860 | 0.0928 | 0.1007 |
| **5** | 0.1103 | 0.0951 | 0.0872 | 0.0838 | 0.0995 | 0.1100 | 0.1066 |
| **6** | **0.1058** | 0.1241 | 0.1176 | 0.1169 | 0.1283 | 0.1057 | 0.1176 |
| **7** | 0.1173 | **0.1214** | 0.1268 | 0.1426 | 0.1336 | 0.1177 | 0.1214 |
| **8** | 0.1183 | 0.1361 | 0.1298 | 0.1483 | 0.1483 | 0.1405 | 0.1259 |
| **9** | 0.1199 | 0.1439 | 0.1605 | 0.1535 | 0.1607 | **0.1232** | **0.1254** |
| **10** | 0.1285 | 0.1740 | 0.1901 | 0.1850 | **0.1347** | **0.1038** | **0.0867** |
| **M10-M1** | 0.0542 | 0.1032 | 0.1341 | 0.1386 | 0.0938 | 0.0187 | -0.0045 |
<br>
上表中的 M10 就是上一節分析時的贏家投資組合，而 M1 就是輸家投資組合，在這節中我們把訊號維度展開，觀察所有組別 (M1 至 M10) 的報酬分布。為了方便觀察單調性，我將每組不符合單調性之處加粗。

首先可以觀察到的是除了 $J=1$ 外，其他組別都存在 M1 > M2 的狀況，這表示過去表現最差的輸家 M1 未來一個月會有報酬反轉，儘管不多但仍高於表現次差的輸家 M2。而這樣的跌深反彈或許也能解釋為何台股的多空組合報酬不如美股。

以報酬單調性而言，在 $J \leq 9$ 個月時，可以觀察到報酬大致呈現單調性，儘管中間組別偶有例外但差距不大，表示策略確實捕捉到了投資人反應不足的潛在獲利。但當 $J \geq 12$ 時，可以發現最強的 M10 甚至 M9 會有報酬反轉且差異明顯，這表示當形成期超過一定程度時，策略訊號的預測力會下降，捕捉到更多長期大漲而開始均值回歸的標的。

以多空擴散程度來說 (M10-M1)，$J=6$ 和 $J=9$ 的擴散程度最大，資訊鑑別度最好。

### 條件排序分析
條件排序分析的目的是去檢視**在控制另一因子後，主要策略的表現是否仍然有效**。如果不控制，我們會擔心所謂的動能贏家會不會只是捕捉到其他因子所帶來的溢酬，而非動能訊號本身具有預測能力。

#### 小型股 vs 動能贏家
一種可能的說法是：動能贏家之所以表現好，只是因為小型股在贏家組合中的比例偏高。由於小型股的股價波動大，通常不是大漲就是大跌，更容易被選入動能策略中的贏家組合和輸家組合，又因為小型股存在所謂的**小型股溢酬**，所以本質上動能策略只是一種選擇小型股的手段，而非動能訊號本身具有預測能力。

#### 高 Beta 股 vs 動能贏家
另一種可能的說法是：在多頭市場中，高 Beta 股本來就因為放大市場漲幅而持續表現好，動能策略在多頭環境下自然把這些股票挑為贏家，所以動能報酬可能只是**系統性市場風險的報酬**，而非動能本身。

#### 建構條件排序
我們採用 5x5 的分組方式進行條件排序，步驟如下：

- 針對需控制的因子 (市值、Beta) 由小到大分成 5 組
- 再針對上述每組的股票池，依照動能由弱到強再分成 5 組

::: {.callout-tip}
## 為何不用 10x10
由於通過股票池濾網的標的數量約為 1 千多檔，因此我們選擇 5x5 的分組方式，以確保每個組別的樣本數量足夠。若使用 10x10 的分組方式，則每組僅會有 10 多檔股票，無法有效平衡投資組合內的個股風險。
:::

#### 解讀結果
在控制因子的每一組內，動能最強的 M5 都要持續優於 M1，而且這個差距要在 5 組之間都成立，才能說動能訊號有獨立的預測力。如果 M5-M1 差距在某些控制組消失，則表示動能溢酬與該因子存在交互作用；如果M5-M1 差距在所有控制組都消失，則動能溢酬大部分被該因子解釋，訊號本身沒有獨立預測力。

此外我們也能近一步觀察各組的報酬單調性如何，檢視動能訊號的鑑別度，但這屬於輔助觀察，主要還是看 M5-M1 差距。

::: {.panel-tabset}
## 控制小型股

## 控制高 Beta 股


[^1]: Jegadeesh, N., & Titman, S. (1993). Returns to buying winners and selling losers: Implications for stock market efficiency. The Journal of Finance, 48(1), 65-91.
[^2]: Gong, Q., Liu, M., & Liu, Q. (2015). Momentum is really short-term momentum. Journal of Banking & Finance, 50, 169-182.
[^3]: Jegadeesh, N., & Titman, S. (2001). Profitability of momentum strategies: An evaluation of alternative explanations. The Journal of Finance, 56(2), 699-720.
[^4]: 文章版面有限，詳見策略程式碼，裡面包含所有分析結果與實作細節。
